### ISSUE TITLE
Add call status 

### ISSUE THREAD

**Issue by pepsonEL** [tomasbedrich/home-assistant-hikconnect#4]
If available also good will be add status VideoIntercom to this integration. When user press button to call it should also send info to Home Assistatnt.... maybe as binarysensor which change from OFF status to ON status ?

**Comment by tomasbedrich** [comment]
Copying from https://community.home-assistant.io/t/hik-connect/342202/8?u=tomasbedrich:

> What is worse, is the “ring” event (if we define “event” as something which is pushed from server to client). I have not found any such event yet – but I haven’t been looking for it either. :smiley: There is only `get_call_status(...) API endpoint`[https://github.com/tomasbedrich/hikconnect], but it would require status polling to deliver ring event to Home Assistant. I dislike this solution, therefore I postponed implementation of ring event until I have time to explore how Hik-Connect app handles it.

**Comment by tomasbedrich** [comment]
Today I performed an experiment with simple `get_call_status` polling. It behaves like this:

```
# At rest looks like this (before any action + after cancelling the call from door station):
# {"apiId":1,"callStatus":1,"verFlag":1,"callerInfo":{"buildingNo":0,"floorNo":0,"zoneNo":0,"unitNo":0,"devNo":0,"devType":0,"lockNum":0},"rc":1}

# When ringing looks like this:
# {"apiId":1,"callStatus":2,"verFlag":1,"callerInfo":{"buildingNo":1,"floorNo":0,"zoneNo":1,"unitNo":1,"devNo":1,"devType":1,"lockNum":1},"rc":1}
```

I want to perform additional experiments before I understand how it works and implement something on top of that:

- [ ] How `buildingNo,zoneNo,unitNo,devNo,lockNum` maps to devices and cameras returned in other API calls – try ringing another door station.
- [ ] What happens when call is answered (= call in progress).
- [ ] What happens when call is declined.

**Comment by Klagio** [comment]
doorbell press event would very very good feature to have

**Comment by Shamshala** [comment]
Definitely one of the must-have features. Any way to help implement this?

**Comment by pergolafabio** [comment]
guys , you can use this command to get callstatus : 

https://apiieu.hik-connect.com/v3/devconfig/v1/call/QXXXXX/status

**Comment by pepsonEL** [comment]
But how.... Can you explain more ?

**Comment by pergolafabio** [comment]
you can create your own component, just create a new function in this file

https://github.com/tomasbedrich/hikconnect/blob/main/hikconnect/api.py

its a bit of copy/paste , looks almost identical as the remote unlock

**Comment by pepsonEL** [comment]
I dont know how.....

**Comment by pergolafabio** [comment]
do you see the sessionID somewhere in this integration? normally @tomasbedrich  is using it somewhere, maybe you can find it as an attribute ... , then you can use it in a sensor like below for example, this is how i did it before


```
  - platform: command_line
    command: >
      curl
      --header "sessionId: {{ state_attr('sensor.hikconnect_login', 'loginSession').sessionId }}"
      "https://apiieu.hik-connect.com/v3/devconfig/v1/call/YOURSERIALNR/status"
    name: hikconnect_callstatus
    scan_interval: 3
    value_template: "Callstatus" 
    json_attributes:
      - data
```

**Comment by pepsonEL** [comment]
No i dont see in integration.... sessionID

**Comment by pergolafabio** [comment]
you can create your onw session ID sensor, i posted that on forum a long time ago

```
  - platform: rest
    name: hikconnect_login
    scan_interval: 3600
    resource: "https://apiieu.hik-connect.com/v3/users/login/v2"
    headers:
      customno: 1000002
      appChannel: "hikvision"
      Content-Type: "application/x-www-form-urlencoded"
      featureCode: "b547bcdd76b2f2c93e0956114a6f8665"
      lang: "en-US"
      clientVersion: "4.14.1.0407"
      appId: "HikConnect"
      sessionId: ""
      clientType: 55
      clientNo: "google_play"
      areaId: 111
      netType: "WIFI"
      osVersion: "5.1.1"   
    method: POST
    payload: !secret hikvision_payload
    value_template: "Hikconnect Login"    
    json_attributes:
    - loginSession
```
