### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by beccsjb** [tomasbedrich/home-assistant-hikconnect#9]
Im having issues right at the start with logging in when the integration is first launched.

my login credentials are correct as verified by logging in via the hik connect website.

**Comment by tomasbedrich** [comment]
Hi, would you mind helping me with debugging on your side? I need you to add this to your Home Assistant config:

```
logger:
  logs:
    hikconnect: debug
    custom_components.hikconnect: debug
```

Please send me the logs so that I know what is wrong. Also a few screenshots may be helpful. Please send it to e-mail ja@tbedrich.cz. Beware there are potentially sensitive info there: `session_id, refresh_session_id` + your intercom device ID + serial number.
